services: 
    mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            SA_PASSWORD: "Password1234@"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"
            MSSQL_DATA_DIR: "/var/opt/mssql"
        ports:
            - "1433:1433"
        volumes:
            - mssql:/var/opt/mssql
volumes:
    mssql:        